import type { PlatformConnectorDescriptor, PlatformConnectorId } from "./types";

export const platformConnectors: PlatformConnectorDescriptor[] = [
  {
    id: "youtube",
    name: "YouTube Data API",
    status: "planned",
    authMethods: ["oauth", "api_key"],
    truthLevel: "official_api",
    sourceUrl: "https://developers.google.com/youtube/v3/getting-started",
    metrics: ["views", "likes", "comments", "followers", "impressions"],
    syncCadence: "daily",
    setupNotes: [
      "Criar projeto Google Cloud separado do app principal.",
      "Usar OAuth para dados privados do canal.",
      "Guardar quota usada por rotina para nao travar sincronizacoes.",
    ],
    risks: [
      "quota diaria padrao pode limitar buscas e uploads",
      "nem todo dado de Studio/Analytics aparece no Data API",
    ],
  },
  {
    id: "instagram",
    name: "Instagram Graph API",
    status: "planned",
    authMethods: ["oauth"],
    truthLevel: "official_api",
    sourceUrl: "https://developers.facebook.com/docs/instagram-platform/",
    metrics: ["impressions", "reach", "likes", "comments", "shares", "followers", "engagement_rate"],
    syncCadence: "daily",
    setupNotes: [
      "Usar conta profissional/creator conectada ao ecossistema Meta.",
      "Passar por revisao de permissoes se precisar insights avancados.",
      "Guardar token longo e renovacao em backend seguro.",
    ],
    risks: [
      "Meta exige permissoes e revisao para varios dados",
      "APIs mudam versoes e podem quebrar fluxos se nao houver monitoramento",
    ],
  },
  {
    id: "tiktok",
    name: "TikTok Display API",
    status: "planned",
    authMethods: ["oauth"],
    truthLevel: "official_api",
    sourceUrl: "https://developers.tiktok.com/doc/display-api-overview",
    metrics: ["views", "likes", "comments", "shares"],
    syncCadence: "daily",
    setupNotes: [
      "Comecar com Display API para perfil e videos autorizados.",
      "Separar creator data, ads data e posting data em conectores diferentes.",
      "Usar webhooks quando disponivel para reduzir polling.",
    ],
    risks: [
      "dados publicos em massa sao restritos",
      "alguns endpoints exigem aprovacao e escopo especifico",
    ],
  },
  {
    id: "google-analytics",
    name: "Google Analytics Data API",
    status: "planned",
    authMethods: ["oauth", "service_account"],
    truthLevel: "official_api",
    sourceUrl: "https://developers.google.com/analytics/devguides/reporting/",
    metrics: ["views", "clicks", "conversions", "revenue", "engagement_rate"],
    syncCadence: "daily",
    setupNotes: [
      "Conectar propriedades GA4 dos sites/landing pages.",
      "Importar eventos de afiliado quando possivel.",
      "Padronizar UTM para todo conteudo criado pelo OS.",
    ],
    risks: ["dados dependem de tagueamento correto", "atrasos e thresholds podem alterar relatorios"],
  },
  {
    id: "search-console",
    name: "Google Search Console API",
    status: "planned",
    authMethods: ["oauth", "service_account"],
    truthLevel: "official_api",
    sourceUrl: "https://developers.google.com/webmaster-tools",
    metrics: ["clicks", "impressions", "ctr"],
    syncCadence: "daily",
    setupNotes: [
      "Conectar dominios verificados.",
      "Guardar consultas, paginas e paises por periodo.",
      "Cruzar SEO com ideias de conteudo e funil de afiliacao.",
    ],
    risks: ["dados agregados podem ter anonimato/limites", "exige propriedade verificada"],
  },
  {
    id: "meta-ads",
    name: "Meta Marketing API",
    status: "ready_later",
    authMethods: ["oauth"],
    truthLevel: "official_api",
    sourceUrl: "https://developers.facebook.com/docs/marketing-apis/",
    metrics: ["spend", "impressions", "reach", "clicks", "ctr", "conversions", "revenue"],
    syncCadence: "daily",
    setupNotes: [
      "Usar apenas quando comecar campanhas pagas.",
      "Separar metricas organicas de pagas.",
      "Guardar campanha, conjunto, criativo e custo por resultado.",
    ],
    risks: ["revisao de app e permissao podem demorar", "dados dependem de pixel/conversions API"],
  },
  {
    id: "tiktok-ads",
    name: "TikTok Business API",
    status: "ready_later",
    authMethods: ["oauth"],
    truthLevel: "official_api",
    sourceUrl: "https://ads.tiktok.com/marketing_api/docs",
    metrics: ["spend", "impressions", "clicks", "ctr", "conversions", "revenue"],
    syncCadence: "daily",
    setupNotes: [
      "Usar quando houver TikTok Ads ou catalogo.",
      "Guardar criativos e relatorios de material.",
      "Comparar custo por criativo com o roteiro/IA que gerou o ativo.",
    ],
    risks: ["escopos e acesso podem depender de conta Business", "relatorios podem ter atraso"],
  },
  {
    id: "affiliate-network",
    name: "Redes de Afiliado",
    status: "manual_first",
    authMethods: ["api_key", "csv_import", "manual"],
    truthLevel: "official_export",
    sourceUrl: "https://support.google.com/analytics/answer/10917952",
    metrics: ["clicks", "conversions", "revenue"],
    syncCadence: "daily",
    setupNotes: [
      "Comecar importando CSV das plataformas que nao tiverem API simples.",
      "Padronizar links com UTM e subid para rastrear conteudo de origem.",
      "Depois criar conectores por Hotmart, Amazon, Shopee, Kiwify ou outra rede usada.",
    ],
    risks: ["cada rede tem API e qualidade de dados diferente", "sem UTM/subid a atribuicao fica fraca"],
  },
  {
    id: "manual-csv",
    name: "Importacao CSV Manual",
    status: "manual_first",
    authMethods: ["csv_import", "manual"],
    truthLevel: "official_export",
    sourceUrl: "https://en.wikipedia.org/wiki/Comma-separated_values",
    metrics: [
      "views",
      "watch_time",
      "likes",
      "comments",
      "shares",
      "followers",
      "clicks",
      "impressions",
      "reach",
      "ctr",
      "conversions",
      "revenue",
      "spend",
      "rpm",
      "engagement_rate",
    ],
    syncCadence: "manual",
    setupNotes: [
      "Serve como ponte ate OAuth/API ficar pronto.",
      "Guardar arquivo bruto no storage para auditoria.",
      "Mapear colunas por plataforma para evitar dados falsos ou duplicados.",
    ],
    risks: ["manual e sujeito a erro humano", "nao substitui integracao oficial no longo prazo"],
  },
];

export const getPlatformConnector = (id: PlatformConnectorId) =>
  platformConnectors.find((connector) => connector.id === id);

export const officialApiConnectors = platformConnectors.filter(
  (connector) => connector.truthLevel === "official_api"
);
