import type { AiModelDescriptor, AiProviderDescriptor } from "./types";

export const aiProviderRegistry: AiProviderDescriptor[] = [
  {
    id: "google-gemini",
    name: "Google Gemini",
    status: "planned",
    website: "https://ai.google.dev/gemini-api/docs/pricing",
    envKeys: ["GEMINI_API_KEY"],
    modalities: ["text", "image", "vision", "embedding", "agent"],
    strengths: ["multimodal reasoning", "Google ecosystem", "fast drafts", "long context"],
    costNotes: "Strong default while your current Google plan is active; API billing must still be capped.",
    rightsProfile: "review_required",
    setupNotes: "Keep keys server-side. Use Google billing budgets before enabling video/image spend.",
  },
  {
    id: "google-veo",
    name: "Google Veo",
    status: "planned",
    website: "https://ai.google.dev/gemini-api/docs/pricing",
    envKeys: ["GEMINI_API_KEY", "GOOGLE_CLOUD_PROJECT"],
    modalities: ["video"],
    strengths: ["premium video generation", "cinematic outputs", "Google media stack"],
    costNotes: "Use only for final or high-value generations; video credits can drain fast.",
    rightsProfile: "review_required",
    setupNotes: "Route drafts to cheaper video/image models first, then upgrade the best prompt to Veo.",
  },
  {
    id: "openai",
    name: "OpenAI",
    status: "planned",
    website: "https://openai.com/api/pricing/",
    envKeys: ["OPENAI_API_KEY"],
    modalities: ["text", "image", "audio", "speech_to_text", "vision", "agent"],
    strengths: ["structured agents", "reasoning", "image generation", "speech and transcription"],
    costNotes: "Useful as a high-reliability router target and final reviewer; watch token usage.",
    rightsProfile: "review_required",
    setupNotes: "Use server routes, response schemas and per-request budget guards.",
  },
  {
    id: "anthropic",
    name: "Anthropic Claude",
    status: "planned",
    website: "https://docs.anthropic.com/en/docs/about-claude/pricing",
    envKeys: ["ANTHROPIC_API_KEY"],
    modalities: ["text", "vision", "agent", "safety"],
    strengths: ["deep writing", "long-form analysis", "review", "policy/safety reasoning"],
    costNotes: "Best used for premium review, planning and complex reasoning, not every draft.",
    rightsProfile: "review_required",
    setupNotes: "Pair with cheaper draft models and call only when quality threshold requires it.",
  },
  {
    id: "runway",
    name: "Runway API",
    status: "planned",
    website: "https://docs.dev.runwayml.com/guides/pricing",
    envKeys: ["RUNWAYML_API_SECRET"],
    modalities: ["image", "video", "audio"],
    strengths: ["video generation", "image-to-video", "creative media pipeline"],
    costNotes: "Credit based. Good middle layer between cheap drafts and expensive final video.",
    rightsProfile: "review_required",
    setupNotes: "Use for simulation previews and mid-tier final assets after prompt approval.",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    status: "planned",
    website: "https://elevenlabs.io/pricing/api/",
    envKeys: ["ELEVENLABS_API_KEY"],
    modalities: ["audio", "agent"],
    strengths: ["premium voices", "voice cloning", "voice agents", "dubbing"],
    costNotes: "Quality is excellent, but use after script lock to avoid wasting characters/credits.",
    rightsProfile: "review_required",
    setupNotes: "Keep as final voice provider; use cheaper TTS/local voices for drafts.",
  },
  {
    id: "deepgram",
    name: "Deepgram",
    status: "planned",
    website: "https://deepgram.com/pricing",
    envKeys: ["DEEPGRAM_API_KEY"],
    modalities: ["speech_to_text", "audio", "agent"],
    strengths: ["transcription", "realtime speech", "lower-cost voice workflows"],
    costNotes: "Good candidate for transcription and draft/utility voice at predictable cost.",
    rightsProfile: "commercial_safe",
    setupNotes: "Use for audio ingestion, subtitles and call/voice-agent experiments.",
  },
  {
    id: "replicate",
    name: "Replicate",
    status: "planned",
    website: "https://replicate.com/pricing",
    envKeys: ["REPLICATE_API_TOKEN"],
    modalities: ["image", "video", "audio", "speech_to_text", "music"],
    strengths: ["open-source models", "experimentation", "model variety"],
    costNotes: "Pay per model/runtime; great laboratory before committing to a premium provider.",
    rightsProfile: "unknown",
    setupNotes: "Whitelist models and store license notes per model before production use.",
  },
  {
    id: "fal",
    name: "fal.ai",
    status: "planned",
    website: "https://docs.fal.ai/documentation/model-apis/pricing",
    envKeys: ["FAL_KEY"],
    modalities: ["image", "video", "audio"],
    strengths: ["fast media models", "image/video experiments", "serverless GPU"],
    costNotes: "Pay per successful output or GPU time depending on model.",
    rightsProfile: "unknown",
    setupNotes: "Use as a fast creative model lab with per-model allowlists.",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    status: "planned",
    website: "https://openrouter.ai/pricing",
    envKeys: ["OPENROUTER_API_KEY"],
    modalities: ["text", "vision", "agent"],
    strengths: ["many LLMs behind one API", "fallbacks", "model comparison"],
    costNotes: "Good aggregator, but still log every model used and its price.",
    rightsProfile: "review_required",
    setupNotes: "Use for fallback access, never as the only source of cost truth.",
  },
  {
    id: "together",
    name: "Together AI",
    status: "planned",
    website: "https://www.together.ai/pricing",
    envKeys: ["TOGETHER_API_KEY"],
    modalities: ["text", "embedding", "agent"],
    strengths: ["open models", "batch/inference", "cost-effective drafts"],
    costNotes: "Candidate for cheap draft agents and summarization at scale.",
    rightsProfile: "unknown",
    setupNotes: "Use with model allowlists and quality gates.",
  },
  {
    id: "mistral",
    name: "Mistral AI",
    status: "planned",
    website: "https://mistral.ai",
    envKeys: ["MISTRAL_API_KEY"],
    modalities: ["text", "embedding", "agent"],
    strengths: ["European provider", "efficient text models", "structured outputs"],
    costNotes: "Good alternative for drafts, classification and multilingual workflows.",
    rightsProfile: "review_required",
    setupNotes: "Add exact model pricing before enabling production routing.",
  },
  {
    id: "groq",
    name: "Groq",
    status: "planned",
    website: "https://groq.com",
    envKeys: ["GROQ_API_KEY"],
    modalities: ["text", "speech_to_text", "agent"],
    strengths: ["very low latency", "draft agents", "quick classification"],
    costNotes: "Useful for fast, cheap intermediate steps where quality is not final.",
    rightsProfile: "unknown",
    setupNotes: "Use for fast routing/classification and keep final review elsewhere.",
  },
  {
    id: "local",
    name: "Local/Open-source",
    status: "planned",
    website: "https://ollama.com",
    envKeys: ["LOCAL_AI_BASE_URL"],
    modalities: ["text", "embedding", "speech_to_text", "audio"],
    strengths: ["private drafts", "no per-token API bill", "offline experimentation"],
    costNotes: "Cheapest for drafts if your machine can handle it; hardware/electricity still matter.",
    rightsProfile: "private_only",
    setupNotes: "Ideal for first-pass agents, local embeddings and private knowledge base search.",
  },
];

export const aiModelRegistry: AiModelDescriptor[] = [
  {
    id: "gemini-default-fast",
    providerId: "google-gemini",
    displayName: "Gemini Fast Draft",
    status: "planned",
    modalities: ["text", "vision", "image"],
    taskTypes: ["idea_generation", "strategy", "scriptwriting", "copywriting", "analysis", "platform_data_analysis", "translation"],
    qualityTier: "standard",
    costTier: "low",
    latencyTier: "fast",
    rightsProfile: "review_required",
    strengths: ["fast drafts", "multimodal prompts", "Google ecosystem"],
    limits: ["API billing is separate from many consumer plans", "requires budget cap"],
  },
  {
    id: "gemini-premium-review",
    providerId: "google-gemini",
    displayName: "Gemini Premium Review",
    status: "planned",
    modalities: ["text", "vision", "agent"],
    taskTypes: ["analysis", "copyright_review", "quality_review", "automation_agent", "strategy"],
    qualityTier: "premium",
    costTier: "medium",
    latencyTier: "normal",
    rightsProfile: "review_required",
    strengths: ["final review", "long context", "agent planning"],
    limits: ["not ideal for uncontrolled loops without spend guard"],
  },
  {
    id: "veo-final-video",
    providerId: "google-veo",
    displayName: "Veo Final Video",
    status: "planned",
    modalities: ["video"],
    taskTypes: ["video_generation", "video_editing"],
    qualityTier: "premium",
    costTier: "premium",
    latencyTier: "slow",
    rightsProfile: "review_required",
    strengths: ["cinematic video", "high-end final assets"],
    limits: ["expensive", "must require prompt approval and budget lock"],
  },
  {
    id: "openai-strategy-agent",
    providerId: "openai",
    displayName: "OpenAI Strategy Agent",
    status: "planned",
    modalities: ["text", "vision", "agent"],
    taskTypes: ["strategy", "analysis", "automation_agent", "quality_review", "platform_data_analysis"],
    qualityTier: "premium",
    costTier: "medium",
    latencyTier: "normal",
    rightsProfile: "review_required",
    strengths: ["structured agents", "tool use", "reasoning"],
    limits: ["requires token budgeting and server-side secrets"],
  },
  {
    id: "openai-media-pack",
    providerId: "openai",
    displayName: "OpenAI Media Pack",
    status: "planned",
    modalities: ["image", "audio", "speech_to_text"],
    taskTypes: ["image_generation", "image_editing", "voiceover", "speech_to_text", "quality_review"],
    qualityTier: "premium",
    costTier: "medium",
    latencyTier: "normal",
    rightsProfile: "review_required",
    strengths: ["image generation", "transcription", "voice workflow"],
    limits: ["verify commercial policy and current model pricing before production"],
  },
  {
    id: "claude-deep-review",
    providerId: "anthropic",
    displayName: "Claude Deep Review",
    status: "planned",
    modalities: ["text", "vision", "safety"],
    taskTypes: ["analysis", "copyright_review", "quality_review", "strategy", "scriptwriting"],
    qualityTier: "specialist",
    costTier: "high",
    latencyTier: "normal",
    rightsProfile: "review_required",
    strengths: ["deep critique", "long-form writing", "risk review"],
    limits: ["not for every draft; use as a gate"],
  },
  {
    id: "runway-video-draft",
    providerId: "runway",
    displayName: "Runway Video Draft",
    status: "planned",
    modalities: ["video", "image", "audio"],
    taskTypes: ["video_generation", "video_editing", "image_generation", "voiceover"],
    qualityTier: "standard",
    costTier: "medium",
    latencyTier: "slow",
    rightsProfile: "review_required",
    strengths: ["visual previews", "creative variants", "video pipeline"],
    limits: ["credit-based pricing", "still needs final quality review"],
  },
  {
    id: "elevenlabs-final-voice",
    providerId: "elevenlabs",
    displayName: "ElevenLabs Final Voice",
    status: "planned",
    modalities: ["audio", "agent"],
    taskTypes: ["voiceover", "translation", "quality_review"],
    qualityTier: "premium",
    costTier: "high",
    latencyTier: "normal",
    rightsProfile: "review_required",
    strengths: ["premium narration", "voice cloning", "dubbing"],
    limits: ["run only after script approval", "credits can be wasted by repeated edits"],
  },
  {
    id: "deepgram-audio-utility",
    providerId: "deepgram",
    displayName: "Deepgram Audio Utility",
    status: "planned",
    modalities: ["speech_to_text", "audio"],
    taskTypes: ["speech_to_text", "voiceover", "quality_review"],
    qualityTier: "standard",
    costTier: "low",
    latencyTier: "fast",
    rightsProfile: "commercial_safe",
    strengths: ["transcription", "subtitles", "audio ingestion"],
    limits: ["voice style may not replace premium narration"],
  },
  {
    id: "replicate-model-lab",
    providerId: "replicate",
    displayName: "Replicate Model Lab",
    status: "experimental",
    modalities: ["image", "video", "audio", "music"],
    taskTypes: ["image_generation", "image_editing", "video_generation", "music_generation", "voiceover"],
    qualityTier: "standard",
    costTier: "medium",
    latencyTier: "normal",
    rightsProfile: "unknown",
    strengths: ["model variety", "open-source experimentation", "specialized workflows"],
    limits: ["model licenses vary", "quality and speed vary per model"],
  },
  {
    id: "fal-creative-lab",
    providerId: "fal",
    displayName: "fal Creative Lab",
    status: "experimental",
    modalities: ["image", "video", "audio"],
    taskTypes: ["image_generation", "image_editing", "video_generation", "video_editing", "voiceover"],
    qualityTier: "standard",
    costTier: "medium",
    latencyTier: "fast",
    rightsProfile: "unknown",
    strengths: ["fast media experiments", "many image/video models"],
    limits: ["license review required per model"],
  },
  {
    id: "openrouter-fallback-llm",
    providerId: "openrouter",
    displayName: "OpenRouter Fallback LLM",
    status: "planned",
    modalities: ["text", "vision", "agent"],
    taskTypes: ["idea_generation", "strategy", "scriptwriting", "analysis", "translation", "automation_agent"],
    qualityTier: "standard",
    costTier: "medium",
    latencyTier: "normal",
    rightsProfile: "review_required",
    strengths: ["provider fallback", "model comparison", "quick experimentation"],
    limits: ["must log actual routed model", "do not rely on aggregator as source of truth"],
  },
  {
    id: "local-private-draft",
    providerId: "local",
    displayName: "Local Private Draft",
    status: "planned",
    modalities: ["text", "embedding"],
    taskTypes: ["idea_generation", "strategy", "scriptwriting", "analysis", "embedding", "platform_data_analysis"],
    qualityTier: "draft",
    costTier: "free_local",
    latencyTier: "normal",
    rightsProfile: "private_only",
    strengths: ["private first pass", "zero API bill", "knowledge base indexing"],
    limits: ["quality depends on hardware/model", "not a final reviewer"],
  },
  {
    id: "groq-fast-classifier",
    providerId: "groq",
    displayName: "Groq Fast Classifier",
    status: "planned",
    modalities: ["text", "agent"],
    taskTypes: ["analysis", "platform_data_analysis", "quality_review", "translation"],
    qualityTier: "draft",
    costTier: "low",
    latencyTier: "instant",
    rightsProfile: "unknown",
    strengths: ["fast classification", "routing helpers", "cheap first pass"],
    limits: ["not the final authority for complex creative decisions"],
  },
  {
    id: "together-open-draft",
    providerId: "together",
    displayName: "Together Open Draft",
    status: "planned",
    modalities: ["text", "embedding", "agent"],
    taskTypes: ["idea_generation", "copywriting", "scriptwriting", "analysis", "embedding"],
    qualityTier: "draft",
    costTier: "low",
    latencyTier: "fast",
    rightsProfile: "unknown",
    strengths: ["low-cost open models", "summaries", "bulk drafting"],
    limits: ["final quality varies by model"],
  },
];

export const getAiProviderById = (providerId: string) =>
  aiProviderRegistry.find((provider) => provider.id === providerId);

export const getAiModelById = (modelId: string) =>
  aiModelRegistry.find((model) => model.id === modelId);
